version: "3.7"

services:
  web:
    image: nginx:alpine
    ports:
      - 8083:80
    volumes:
      - type: bind
        source: ./
        target: /var/www
        consistency: cached
      - ./etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - www
  phpfpm:
    build:
      context: ./
      dockerfile: php.dockerfile
    volumes:
      - type: bind
        source: ./
        target: /var/www
        consistency: cached
      - ./tmp/grinds:/tmp/grinds
    networks:
      - www
    extra_hosts:
        host.docker.internal: host-gateway
    working_dir: /var/www
    links:
      - db
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment:
        PGADMIN_DEFAULT_EMAIL: user@example.com
        PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - www
  db:
    image: postgres:14.5-alpine
    restart: always
    environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_DB: task_tracker_db
#    volumes:
#        - ./postgres-data:/var/lib/postgresql/data
    ports:
        - "5432:5432"
    networks:
      - www
volumes:
  db-data:
networks:
  www:
